name: Build/release

on:
  push:
    tags:
      - '*@*'

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Build Mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx run-many --target=build --configuration=release-mac

  build-linux:
    needs: build-mac
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Build Linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx run-many --target=build --configuration=release-linux
